### ISSUE TITLE
Plus de 2 couples ip/noms de domaines

### ISSUE THREAD

**Issue by anto1ne** [zb2oby/hosts#3]
Est ce possible de modifier le script afin de pourvoir ajouter plus que 2 couples ip/noms de domaines ?

**Comment by zb2oby** [comment]
tout est possible. il faudrais modifier un peu la façon de faire et boucler tant qu'on veut ajouter des couples.

**Comment by zb2oby** [comment]
Je viens de pousser des modifications permettant d'enregistrer autant de SSID et autant de couple IP/Domaine que nécessaire sur la branche "development". Si tu veux tester et me dire si cela correspond bien à ce qui tu voulais avant que je merge dans le master ?
Merci

**Comment by anto1ne** [comment]
je viens de tester et ça correspond bien à ma demande,
le script a bien fonctionné de bout en bout
merci beaucoup, ce script est vraiment cool
